Brand filter
janekkerner/RubyLoversShop pull request #4
Opened 2021-06-07 16:36 UTC by janekkerner

sprint 1, task 3

2021-06-08 08:34 UTC, oskarlakner commented on app/controllers/pages_controller.rb
> +    if @filters[:category_id].nil? && @filters[:brand_id].nil?
dlaczego nie oparles tego od razu o params?

2021-06-08 08:45 UTC, oskarlakner requested changes
Janek, wierze ze dziala fajnie, ale moim zdaniem to nie moze przejsc dalej, bo bedzie trudne w utrzymaniu. Opieranie tez rozwiazania o zmienna instancyjna definiowana gdzies, a potem w jakimś partialu w `/application` opieranie na nim rozwiazania traci smrodem troche. Obczaj Ransack albo searchlight. Mozesz tez podpytac Kube Krzusia jak on to zrobil

2021-06-08 22:15 UTC, janekkerner commented
Zmieniłem implementacje z wykorzystaniem ransacka. Mam nadzieję że teraz będzie lepiej

2021-06-09 07:29 UTC, oskarlakner approved these changes
No i teraz elegancko to wyglada :)

2021-06-10 09:30 UTC, merged